### ISSUE TITLE
Incorrect peer dependency

### ISSUE THREAD

**Issue by krukiv-kut** [pqina/filepond-plugin-image-crop#2]
Hey guys. I've got this kind of warning just now.
How to reproduce:
> yarn add filepond-plugin-image-crop

In results output:
> warning " > filepond-plugin-image-crop@2.0.0" has incorrect peer dependency "filepond@^3.0.0".

In the package.json of this plugin we have:
> "peerDependencies": {"filepond": "^3.0.0"}

Which obviously (if there is no version related issues) should be changed to:
> "peerDependencies": {"filepond": ">=3.x <5.x"}

Like in other plugins.

**Comment by rikschennink** [comment]
Thanks for the detailed report. I forgot to push the image crop changes to npm. Should be fine in a couple of minutes.
